app/apps/sample_web/lib/sample_web/router.ex
defmodule SampleWeb.Router do
  use SampleWeb, :router

  use Kaffy.Routes,
    scope: "/admin",
    pipe_through: [:fetch_current_admin_user, :require_authenticated_admin_user]

  import SampleWeb.AdminUserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SampleWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_admin_user
  end

  pipeline :api do
    plug CORSPlug
    plug :accepts, ["json"]
  end

  scope "/", SampleWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SampleWeb do
  #   pipe_through :api
  # end
  scope "/" do
    pipe_through :api

    forward "/api", Absinthe.Plug, schema: Graphql.Schema

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: Graphql.Schema,
      interface: :simple,
      socket: SampleWeb.UserSocket
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SampleWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", SampleWeb do
    pipe_through [:browser, :redirect_if_admin_user_is_authenticated]

    get "/admin_users/register", AdminUserRegistrationController, :new
    post "/admin_users/register", AdminUserRegistrationController, :create
    get "/admin_users/log_in", AdminUserSessionController, :new
    post "/admin_users/log_in", AdminUserSessionController, :create
    get "/admin_users/reset_password", AdminUserResetPasswordController, :new
    post "/admin_users/reset_password", AdminUserResetPasswordController, :create
    get "/admin_users/reset_password/:token", AdminUserResetPasswordController, :edit
    put "/admin_users/reset_password/:token", AdminUserResetPasswordController, :update
  end

  scope "/", SampleWeb do
    pipe_through [:browser, :require_authenticated_admin_user]

    get "/admin_users/settings", AdminUserSettingsController, :edit
    put "/admin_users/settings", AdminUserSettingsController, :update
    get "/admin_users/settings/confirm_email/:token", AdminUserSettingsController, :confirm_email
  end

  scope "/", SampleWeb do
    pipe_through [:browser]

    delete "/admin_users/log_out", AdminUserSessionController, :delete
    get "/admin_users/confirm", AdminUserConfirmationController, :new
    post "/admin_users/confirm", AdminUserConfirmationController, :create
    get "/admin_users/confirm/:token", AdminUserConfirmationController, :edit
    post "/admin_users/confirm/:token", AdminUserConfirmationController, :update
  end
end

app/apps/sample_web/lib/sample_web/views/layout_view.ex
defmodule SampleWeb.LayoutView do
  use SampleWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

app/apps/sample_web/lib/sample_web/templates/layout/_admin_user_menu.html.heex
<ul>
<%= if @current_admin_user do %>
  <li><%= @current_admin_user.email %></li>
  <li><%= link "Settings", to: Routes.admin_user_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.admin_user_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.admin_user_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.admin_user_session_path(@conn, :new) %></li>
<% end %>
</ul>

app/apps/sample_web/lib/sample_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

app/apps/sample_web/lib/sample_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

app/apps/sample_web/lib/sample_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Sample", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
          <%= render "_admin_user_menu.html", assigns %>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>